@extends('layouts.app')
@section('title','Transactions')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Transactions</div><h1 class="page-title">Inventory transactions</h1><p class="page-subtitle">A searchable, immutable movement history with batch, user, reference, and before/after quantities.</p></div><div class="page-actions">@if(auth()->user()->hasPermission('reports.view'))<a class="btn btn-secondary" href="{{ route('reports.index',['report'=>'transactions']) }}"><x-icon name="report" class="icon-sm" /> Transaction report</a>@endif</div></div>
<form class="card filter-bar" method="GET"><div class="filters" style="grid-template-columns:2fr repeat(3,1fr) auto"><div class="field filter-search"><label for="search">Search transactions</label><div class="input-wrap"><x-icon name="search" class="icon-sm" /><input class="input" id="search" name="search" value="{{ request('search') }}" placeholder="Transaction ID, reference, medicine, batch…"></div></div><div class="field"><label for="type">Type</label><select class="select" id="type" name="type"><option value="">All types</option>@foreach($types as $type)<option value="{{ $type->value }}" @selected(request('type')===$type->value)>{{ $type->label() }}</option>@endforeach</select></div><div class="field"><label for="date_from">From</label><input class="input" id="date_from" name="date_from" type="date" value="{{ request('date_from') }}"></div><div class="field"><label for="date_to">To</label><input class="input" id="date_to" name="date_to" type="date" value="{{ request('date_to') }}"></div><button class="btn btn-primary" type="submit">Apply</button></div></form>
<section class="card"><div class="card-header"><div><h2 class="card-title">{{ number_format($transactions->total()) }} transaction records</h2><p class="card-subtitle">Most recent activity first.</p></div><a class="link" href="{{ route('transactions.index') }}">Clear filters</a></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Transaction ID</th><th>Date & time</th><th>Medicine / batch</th><th>Type</th><th>Quantity</th><th>Stock change</th><th>User</th><th>Reason / reference</th></tr></thead><tbody>
@forelse($transactions as $transaction)<tr><td class="mono">{{ $transaction->transaction_code }}</td><td>{{ $transaction->transacted_at->format('M d, Y') }}<span class="table-secondary">{{ $transaction->transacted_at->format('g:i A') }}</span></td><td><a class="table-primary" href="{{ route('medicines.show',$transaction->medicine) }}">{{ $transaction->medicine->generic_name }}</a><span class="table-secondary mono">{{ $transaction->batch?->batch_number ?? 'No batch' }}</span></td><td><span class="badge {{ in_array($transaction->type,[App\TransactionType::StockOut,App\TransactionType::Dispensed])?'badge-warning':($transaction->type===App\TransactionType::StockIn?'badge-success':'badge-info') }}">{{ $transaction->type->label() }}</span></td><td><strong>{{ number_format($transaction->quantity) }}</strong> {{ $transaction->medicine->unit }}</td><td>{{ $transaction->previous_stock }} → <strong>{{ $transaction->new_stock }}</strong></td><td>{{ $transaction->user?->name ?? 'System' }}</td><td>{{ $transaction->reason ?: $transaction->purpose ?: '—' }}<span class="table-secondary">{{ $transaction->reference_number ?: 'No reference' }}</span></td></tr>
@empty<tr><td colspan="8"><div class="empty-state"><span class="empty-icon"><x-icon name="transaction" /></span><h3>No transactions found</h3><p>Try a wider date range or clear the filters.</p></div></td></tr>@endforelse
</tbody></table></div><x-pagination :paginator="$transactions" /></section>
@endsection
