@extends('layouts.app')
@section('title',$managedUser->exists?'Edit User':'Add User')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('users.index') }}">Users</a><x-icon name="chevron" class="icon-sm" /> {{ $managedUser->exists?'Edit':'Add' }}</div><h1 class="page-title">{{ $managedUser->exists?'Edit user':'Add user' }}</h1><p class="page-subtitle">Assign the least-privileged role that supports this user’s responsibilities.</p></div></div>
<form class="card" method="POST" action="{{ $managedUser->exists?route('users.update',$managedUser):route('users.store') }}">@csrf @if($managedUser->exists)@method('PUT')@endif<div class="card-header"><h2 class="card-title">Account details</h2><x-status-badge :status="$managedUser->status ?? 'active'" /></div><div class="card-body"><div class="form-grid">
<div class="field"><label class="required" for="name">Full name</label><input class="input" id="name" name="name" value="{{ old('name',$managedUser->name) }}" required></div><div class="field"><label class="required" for="email">Email address</label><input class="input" id="email" name="email" type="email" value="{{ old('email',$managedUser->email) }}" required></div>
<div class="field"><label for="phone">Phone number</label><input class="input" id="phone" name="phone" value="{{ old('phone',$managedUser->phone) }}"></div><div class="field"><label for="job_title">Position / job title</label><input class="input" id="job_title" name="job_title" value="{{ old('job_title',$managedUser->job_title) }}"></div>
<div class="field"><label class="required" for="role_id">Role</label><select class="select" id="role_id" name="role_id" required><option value="">Choose role</option>@foreach($roles as $role)<option value="{{ $role->id }}" @selected((string)old('role_id',$managedUser->role_id)===(string)$role->id)>{{ $role->name }} — {{ $role->description }}</option>@endforeach</select></div><div class="field"><label class="required" for="status">Account status</label><select class="select" id="status" name="status" required><option value="active" @selected(old('status',$managedUser->status)==='active')>Active</option><option value="inactive" @selected(old('status',$managedUser->status)==='inactive')>Inactive</option></select></div>
<div class="field"><label class="{{ $managedUser->exists?'':'required' }}" for="password">{{ $managedUser->exists?'New password':'Password' }}</label><input class="input" id="password" name="password" type="password" {{ $managedUser->exists?'':'required' }} autocomplete="new-password"><div class="help-text">{{ $managedUser->exists?'Leave blank to keep the current password.':'Minimum eight characters.' }}</div></div><div class="field"><label class="{{ $managedUser->exists?'':'required' }}" for="password_confirmation">Confirm password</label><input class="input" id="password_confirmation" name="password_confirmation" type="password" {{ $managedUser->exists?'':'required' }} autocomplete="new-password"></div>
</div><div class="form-actions"><a class="btn btn-secondary" href="{{ route('users.index') }}">Cancel</a><button class="btn btn-primary" type="submit">{{ $managedUser->exists?'Save changes':'Create account' }}</button></div></div></form>
@endsection
