@extends('layouts.app')
@section('title','User Management')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Users</div><h1 class="page-title">User management</h1><p class="page-subtitle">Manage account status and role-based access across the inventory system.</p></div><div class="page-actions"><a class="btn btn-secondary" href="{{ route('roles.index') }}"><x-icon name="settings" class="icon-sm" /> Roles & permissions</a><a class="btn btn-primary" href="{{ route('users.create') }}"><x-icon name="plus" class="icon-sm" /> Add user</a></div></div>
<form class="card filter-bar" method="GET"><div class="filters" style="grid-template-columns:2fr 1fr 1fr auto"><div class="field"><label for="search">Search users</label><div class="input-wrap"><x-icon name="search" class="icon-sm" /><input class="input" id="search" name="search" value="{{ request('search') }}" placeholder="Name, email, or position"></div></div><div class="field"><label for="role">Role</label><select class="select" id="role" name="role"><option value="">All roles</option>@foreach($roles as $role)<option value="{{ $role->id }}" @selected((string)request('role')===(string)$role->id)>{{ $role->name }}</option>@endforeach</select></div><div class="field"><label for="status">Status</label><select class="select" id="status" name="status"><option value="">Any status</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select></div><button class="btn btn-primary" type="submit">Apply</button></div></form>
<section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>User</th><th>Role</th><th>Position</th><th>Phone</th><th>Last login</th><th>Status</th><th class="text-right">Actions</th></tr></thead><tbody>
@forelse($users as $managedUser)<tr><td><div style="display:flex;align-items:center;gap:10px"><span class="avatar">{{ str($managedUser->name)->substr(0,1)->upper() }}</span><span><a class="table-primary" href="{{ route('users.show',$managedUser) }}">{{ $managedUser->name }}</a><span class="table-secondary">{{ $managedUser->email }}</span></span></div></td><td><span class="badge badge-info">{{ $managedUser->role?->name ?? 'No role' }}</span></td><td>{{ $managedUser->job_title ?: '—' }}</td><td>{{ $managedUser->phone ?: '—' }}</td><td>{{ $managedUser->last_login_at?->diffForHumans() ?? 'Never' }}</td><td><x-status-badge :status="$managedUser->status" /></td><td><div class="table-actions"><a class="btn btn-secondary btn-icon" href="{{ route('users.show',$managedUser) }}"><x-icon name="eye" class="icon-sm" /></a><a class="btn btn-secondary btn-icon" href="{{ route('users.edit',$managedUser) }}"><x-icon name="edit" class="icon-sm" /></a></div></td></tr>
@empty<tr><td colspan="7"><div class="empty-state"><h3>No users found</h3></div></td></tr>@endforelse
</tbody></table></div><x-pagination :paginator="$users" /></section>
@endsection
