@extends('layouts.app')
@section('title','Stock Adjustment')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Adjustment</div><h1 class="page-title">Stock adjustment</h1><p class="page-subtitle">Correct a specific batch with a signed quantity. Every adjustment is permanently audited.</p></div></div>
<div class="grid grid-2" style="grid-template-columns:1.35fr .65fr"><form class="card" method="POST" action="{{ route('stock.adjustment.store') }}">@csrf<div class="card-header"><div><h2 class="card-title">Adjustment details</h2><p class="card-subtitle">Use a negative number to remove stock and a positive number to add it.</p></div><span class="stat-icon amber"><x-icon name="adjust" /></span></div><div class="card-body"><div class="form-grid">
    <div class="field span-2"><label class="required" for="medicine_batch_id">Medicine batch</label><select class="select" id="medicine_batch_id" name="medicine_batch_id" required><option value="">Choose batch</option>@foreach($batches as $batch)<option value="{{ $batch->id }}" @selected((string)old('medicine_batch_id')===(string)$batch->id)>{{ $batch->medicine->generic_name }} · {{ $batch->batch_number }} · {{ $batch->quantity }} {{ $batch->medicine->unit }} · {{ $batch->storageLocation->name }}</option>@endforeach</select></div>
    <div class="field"><label class="required" for="quantity_difference">Quantity difference</label><input class="input" id="quantity_difference" name="quantity_difference" type="number" value="{{ old('quantity_difference') }}" required placeholder="e.g. -3 or 5"><div class="help-text">The resulting batch quantity cannot be negative.</div></div>
    <div class="field"><label class="required" for="reason">Reason</label><select class="select" id="reason" name="reason" required><option value="">Choose reason</option>@foreach($reasons as $reason)<option value="{{ $reason->value }}" @selected(old('reason')===$reason->value)>{{ $reason->label() }}</option>@endforeach</select></div>
    <div class="field"><label class="required" for="quantity_unit">Count as</label><select class="select" id="quantity_unit" name="quantity_unit"><option value="unit" @selected(old('quantity_unit','unit') === 'unit')>Individual units</option><option value="box" @selected(old('quantity_unit') === 'box')>Boxes</option></select><p class="help-text">Boxes are converted using the medicine's units-per-box setting.</p></div>
    <div class="field span-2"><label class="required" for="notes">Explanation / notes</label><textarea class="textarea" id="notes" name="notes" required>{{ old('notes') }}</textarea><div class="help-text">Be specific; this explanation appears in the audit trail.</div></div>
</div><div class="form-actions"><a class="btn btn-secondary" href="{{ route('dashboard') }}">Cancel</a><button class="btn btn-primary" type="submit"><x-icon name="check" class="icon-sm" /> Apply adjustment</button></div></div></form>
<aside class="card"><div class="card-header"><h2 class="card-title">Accountability controls</h2></div><div class="card-body"><div class="timeline"><div class="timeline-item"><span class="timeline-dot"></span><strong>User attributed</strong><p>{{ auth()->user()->name }} will be recorded.</p></div><div class="timeline-item"><span class="timeline-dot"></span><strong>Before and after</strong><p>Previous and new batch quantities are stored.</p></div><div class="timeline-item"><span class="timeline-dot"></span><strong>Large adjustment alert</strong><p>Changes of 100 or more trigger an alert.</p></div></div></div></aside></div>
@endsection
