@extends('layouts.app')
@section('title', 'Expiration Monitoring')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Expirations</div><h1 class="page-title">Expiration monitoring</h1><p class="page-subtitle">Batch-level expiry visibility. Expired stock is automatically excluded from FEFO dispensing.</p></div><div class="page-actions">@if(auth()->user()->hasPermission('reports.view'))<a class="btn btn-secondary" href="{{ route('reports.index', ['report' => request('status') === 'expired' ? 'expired' : 'expiring']) }}"><x-icon name="report" class="icon-sm" /> Open report</a>@endif</div></div>

<form class="card filter-bar" method="GET"><div class="filters" style="grid-template-columns:2fr 1fr auto"><div class="field filter-search"><label for="search">Search batches</label><div class="input-wrap"><x-icon name="search" class="icon-sm" /><input class="input" id="search" name="search" value="{{ request('search') }}" placeholder="Medicine, batch, supplier, or location"></div></div><div class="field"><label for="status">Expiration window</label><select class="select" id="status" name="status"><option value="">All active batches</option><option value="expired" @selected(request('status') === 'expired')>Already expired</option>@foreach([7, 30, 60, 90] as $days)<option value="{{ $days }}" @selected((string) request('status') === (string) $days)>Within {{ $days }} days</option>@endforeach<option value="safe" @selected(request('status') === 'safe')>Safe / over 90 days</option></select></div><button class="btn btn-primary" type="submit">Apply filter</button></div></form>

<section class="card"><div class="card-header"><div><h2 class="card-title">{{ number_format($batches->total()) }} batches</h2><p class="card-subtitle">Sorted by earliest expiration first.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Medicine</th><th>Batch / lot</th><th>Supplier</th><th>Location</th><th>Quantity</th><th>Expiration</th><th>Time remaining</th><th>Status</th><th class="text-right">Manage</th></tr></thead><tbody>
@forelse($batches as $batch)<tr><td><a class="table-primary" href="{{ route('medicines.show', $batch->medicine) }}">{{ $batch->medicine->generic_name }}</a><span class="table-secondary">{{ $batch->medicine->strength }}</span></td><td><span class="mono">{{ $batch->batch_number }}</span><span class="table-secondary">{{ $batch->lot_number ?: '—' }}</span></td><td>{{ $batch->supplier?->name ?? '—' }}</td><td>{{ $batch->storageLocation->name }}</td><td><strong>{{ $batch->quantity }}</strong> {{ $batch->medicine->unit }}</td><td>{{ $batch->expiration_date->format('M d, Y') }}</td><td>{{ $batch->expiration_date->diffForHumans() }}</td><td><x-status-badge :status="$batch->expirationStatus()" /></td><td><div class="table-actions"><a class="btn btn-secondary btn-sm" href="{{ route('medicines.show', $batch->medicine) }}"><x-icon name="edit" class="icon-sm" /> Manage</a>@if(auth()->user()->hasPermission('stock.receive'))<a class="btn btn-primary btn-sm" href="{{ route('stock.in', ['medicine' => $batch->medicine_id, 'restock' => 1]) }}"><x-icon name="stock-in" class="icon-sm" /> Restock</a>@endif</div></td></tr>@empty<tr><td colspan="9"><div class="empty-state"><span class="empty-icon"><x-icon name="calendar" /></span><h3>No batches in this window</h3><p>Change the filter to see a different expiration range.</p></div></td></tr>@endforelse
</tbody></table></div><x-pagination :paginator="$batches" /></section>
@endsection
