@extends('layouts.app')
@section('title','Stock Out')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Stock out</div><h1 class="page-title">Release or dispense stock</h1><p class="page-subtitle">Automatic FEFO selection uses the earliest eligible expiration and will never dispense expired stock.</p></div><div class="page-actions"><a class="btn btn-secondary" href="{{ route('transactions.index',['type'=>'dispensed']) }}">Dispensing history</a></div></div>
<div class="grid grid-2" style="grid-template-columns:1.5fr .7fr">
<form class="card" method="POST" action="{{ route('stock.out.store') }}">@csrf<div class="card-header"><div><h2 class="card-title">Release details</h2><p class="card-subtitle">The system automatically selects the earliest eligible batch using FEFO.</p></div><span class="stat-icon"><x-icon name="stock-out" /></span></div><div class="card-body"><div class="form-grid">
    <div class="field span-2"><label class="required" for="medicine_id">Medicine</label><select class="select" id="medicine_id" name="medicine_id" data-medicine-select data-batch-target="#medicine_batch_id" data-box-release-medicine data-box-unit-target="#quantity_unit" data-box-help-target="#box-release-help" data-box-reminder-target="#box-quantity-reminder" required><option value="">Choose available medicine</option>@foreach($medicines as $medicine)<option value="{{ $medicine->id }}" data-boxes-available="{{ $medicine->unitsPerBox() !== null && (int) ($medicine->usable_stock ?? 0) >= \App\Models\Medicine::MINIMUM_UNITS_FOR_BOX_RELEASE ? 'true' : 'false' }}" data-box-size="{{ $medicine->unitsPerBox() }}" data-available-units="{{ (int) ($medicine->usable_stock ?? 0) }}" data-inventory-unit="{{ $medicine->unit }}" @selected((string)old('medicine_id',$selectedMedicine)===(string)$medicine->id)>{{ $medicine->generic_name }} — {{ $medicine->strength }} ({{ $medicine->usable_stock ?? 0 }} {{ $medicine->unit }} left)</option>@endforeach</select></div>
    <div class="field"><label class="required" for="quantity">Quantity</label><input class="input" id="quantity" name="quantity" type="number" min="1" value="{{ old('quantity') }}" required></div><div class="field"><label class="required" for="type">Transaction type</label><select class="select" id="type" name="type" data-dispense-type data-recipient-target="#recipient-field" required><option value="dispensed" @selected(old('type','dispensed')==='dispensed')>Dispensed to patient</option><option value="stock_out" @selected(old('type')==='stock_out')>Stock out / released</option></select></div>
    <div class="field span-2"><label class="required" for="quantity_unit">Count as</label><select class="select" id="quantity_unit" name="quantity_unit"><option value="unit" @selected(old('quantity_unit','unit') === 'unit')>Individual units</option><option value="box" @selected(old('quantity_unit') === 'box')>Boxes</option></select><p class="help-text" id="box-release-help">Boxes are available only when at least 100 non-expired units are in stock.</p></div>
    <div class="alert alert-warning span-2" id="box-quantity-reminder" hidden role="status"><x-icon name="alert" /><span data-box-quantity-message></span></div>
    <div class="field span-2" id="recipient-field" @if(old('type','dispensed') !== 'dispensed') hidden @endif><label class="required" for="recipient">Patient name</label><input class="input" id="recipient" name="recipient" value="{{ old('recipient') }}" maxlength="255" placeholder="Enter the patient's name"><p class="help-text">Required only when dispensing to a patient.</p></div>
    <div class="field span-2"><label class="required" for="purpose">Purpose</label><input class="input" id="purpose" name="purpose" value="{{ old('purpose') }}" required placeholder="Patient dispensing, outreach program…"><p class="help-text">The date and time are recorded automatically.</p></div>
</div><div class="form-actions"><a class="btn btn-secondary" href="{{ route('dashboard') }}">Cancel</a><button class="btn btn-primary" type="submit"><x-icon name="stock-out" class="icon-sm" /> Release using FEFO</button></div></div></form>
<aside style="display:grid;gap:18px;align-content:start"><div class="card"><div class="card-header"><h2 class="card-title">FEFO protection</h2></div><div class="card-body"><div class="alert alert-success" style="box-shadow:none"><x-icon name="check" /><span><strong>Expired batches blocked</strong><br>The service only locks and consumes active, non-expired stock.</span></div><p class="card-subtitle">If the requested quantity spans multiple batches, each deduction gets its own linked transaction record.</p></div></div><div class="card"><div class="card-header"><h2 class="card-title">Privacy reminder</h2></div><div class="card-body"><p class="card-subtitle">Use a patient reference number instead of a full clinical record. This inventory system does not replace the facility’s patient record system.</p></div></div></aside>
</div>
@endsection
