@extends('layouts.app')
@section('title','Stock In')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Stock in</div><h1 class="page-title">Receive medicine stock</h1><p class="page-subtitle">Create or replenish a batch. Every receipt generates a transaction, alert, and audit entry.</p></div><div class="page-actions"><a class="btn btn-secondary" href="{{ route('transactions.index',['type'=>'stock_in']) }}">Receipt history</a></div></div>
<div class="grid grid-3" style="grid-template-columns:1.5fr 1fr .7fr">
<form class="card" method="POST" action="{{ route('stock.in.store') }}">@csrf<div class="card-header"><div><h2 class="card-title">Receipt details</h2><p class="card-subtitle">Expired stock cannot be received into active inventory.</p></div><span class="stat-icon teal"><x-icon name="stock-in" /></span></div><div class="card-body"><div class="form-grid">
    @if($restockMedicine)<div class="alert alert-warning span-2" style="box-shadow:none"><x-icon name="alert" /><span><strong>Restock mode: {{ $restockMedicine->generic_name }}</strong><br>{{ number_format((int) $restockMedicine->current_stock) }} {{ $restockMedicine->unit }} currently in stock. Recommended replenishment: {{ number_format($restockMedicine->recommendedReorderQuantity()) }} {{ $restockMedicine->unit }}.</span></div>@endif
    <div class="field span-2"><label class="required" for="medicine_id">Medicine</label><select class="select" id="medicine_id" name="medicine_id" data-box-receipt-medicine data-box-unit-target="#quantity_unit" data-box-help-target="#box-receipt-help" data-box-reminder-target="#box-receipt-reminder" required><option value="">Choose medicine</option>@foreach($medicines as $medicine)<option value="{{ $medicine->id }}" data-box-size="{{ $medicine->unitsPerBox() }}" data-inventory-unit="{{ $medicine->unit }}" @selected((string)old('medicine_id',request('medicine'))===(string)$medicine->id)>{{ $medicine->generic_name }} — {{ $medicine->strength }} ({{ $medicine->medicine_code }})</option>@endforeach</select></div>
    <div class="field span-2"><label class="required" for="batch_number">Batch / lot number</label><input class="input mono" id="batch_number" name="batch_number" value="{{ old('batch_number') }}" required placeholder="e.g. Batch No. or Lot No."><p class="help-text">Enter the manufacturer traceability code printed on the package—use either its batch number or lot number.</p></div>
    <div class="field span-2"><label class="required" for="supplier_id">Supplier</label><select class="select" id="supplier_id" name="supplier_id" required><option value="">Choose supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected((string)old('supplier_id')===(string)$supplier->id)>{{ $supplier->name }}</option>@endforeach</select><p class="help-text">Storage location is assigned automatically using the facility's default active location.</p></div>
    <div class="field"><label class="required" for="quantity">Quantity received</label><input class="input" id="quantity" name="quantity" type="number" min="1" value="{{ old('quantity') }}" required></div><div class="field"><label class="required" for="unit_cost">Unit cost (₱)</label><input class="input" id="unit_cost" name="unit_cost" type="number" min="0" step="0.01" value="{{ old('unit_cost') }}" required></div>
    <div class="field span-2"><label class="required" for="quantity_unit">Count as</label><select class="select" id="quantity_unit" name="quantity_unit"><option value="unit" @selected(old('quantity_unit','unit') === 'unit')>Individual units</option><option value="box" @selected(old('quantity_unit') === 'box')>Boxes</option></select><p class="help-text" id="box-receipt-help">Boxes are converted using the medicine's units-per-box setting. Unit cost remains per individual inventory unit.</p></div>
    <div class="alert alert-warning span-2" id="box-receipt-reminder" hidden role="status"><x-icon name="alert" /><span data-box-receipt-message></span></div>
    <div class="field span-2"><label class="required" for="expiration_date">Expiration date</label><input class="input" id="expiration_date" name="expiration_date" type="date" min="{{ today()->toDateString() }}" value="{{ old('expiration_date') }}" required><p class="help-text">Receipt date is saved automatically as today.</p></div>
</div><div class="form-actions"><a class="btn btn-secondary" href="{{ route('dashboard') }}">Cancel</a><button class="btn btn-primary" type="submit"><x-icon name="check" class="icon-sm" /> Receive stock</button></div></div></form>
<aside class="card"><div class="card-header"><h2 class="card-title">Receiving checklist</h2></div><div class="card-body"><div class="timeline"><div class="timeline-item"><span class="timeline-dot"></span><strong>Verify the medicine</strong><p>Match generic name, strength, form, and packaging.</p></div><div class="timeline-item"><span class="timeline-dot"></span><strong>Inspect the batch</strong><p>Check batch/lot numbers and packaging integrity.</p></div><div class="timeline-item"><span class="timeline-dot"></span><strong>Confirm expiry</strong><p>Expired dates are rejected automatically.</p></div><div class="timeline-item"><span class="timeline-dot"></span><strong>Store correctly</strong><p>Select the physical location used by the facility.</p></div></div></div></aside>
<aside class="card"><div class="card-header"><h2 class="card-title">Secure record</h2></div><div class="card-body"><span class="stat-icon teal"><x-icon name="audit" /></span><p>Received by</p><strong>{{ auth()->user()->name }}</strong><p class="card-subtitle">{{ auth()->user()->role?->name }}</p><hr style="border:0;border-top:1px solid var(--border);margin:18px 0"><p class="card-subtitle">Stock totals, notifications, and the audit log update after submission.</p></div></aside>
</div>
@endsection
