@extends('layouts.app')
@section('title','Stock Out')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Stock out</div><h1 class="page-title">Release or dispense stock</h1><p class="page-subtitle">Automatic FEFO selection uses the earliest eligible expiration and will never dispense expired stock.</p></div><div class="page-actions"><a class="btn btn-secondary" href="{{ route('transactions.index',['type'=>'dispensed']) }}">Dispensing history</a></div></div>
<div class="grid grid-2" style="grid-template-columns:1.5fr .7fr">
<form class="card" method="POST" action="{{ route('stock.out.store') }}">@csrf<div class="card-header"><div><h2 class="card-title">Release details</h2><p class="card-subtitle">Leave batch as automatic to split the quantity across FEFO batches if needed.</p></div><span class="stat-icon"><x-icon name="stock-out" /></span></div><div class="card-body"><div class="form-grid">
    <div class="field span-2"><label class="required" for="medicine_id">Medicine</label><select class="select" id="medicine_id" name="medicine_id" data-medicine-select data-batch-target="#medicine_batch_id" required><option value="">Choose available medicine</option>@foreach($medicines as $medicine)<option value="{{ $medicine->id }}" @selected((string)old('medicine_id',$selectedMedicine)===(string)$medicine->id)>{{ $medicine->generic_name }} — {{ $medicine->strength }} ({{ $medicine->usable_stock ?? 0 }} {{ $medicine->unit }} usable)</option>@endforeach</select></div>
    <div class="field span-2"><label for="medicine_batch_id">Batch selection</label><select class="select" id="medicine_batch_id" name="medicine_batch_id"><option value="">Automatic FEFO (recommended)</option>@foreach($batches as $batch)<option value="{{ $batch->id }}" data-medicine="{{ $batch->medicine_id }}" @selected((string)old('medicine_batch_id')===(string)$batch->id)>{{ $batch->batch_number }} · {{ $batch->quantity }} available · expires {{ $batch->expiration_date->format('M d, Y') }} · {{ $batch->storageLocation->name }}</option>@endforeach</select></div>
    <div class="field"><label class="required" for="quantity">Quantity</label><input class="input" id="quantity" name="quantity" type="number" min="1" value="{{ old('quantity') }}" required></div><div class="field"><label class="required" for="type">Transaction type</label><select class="select" id="type" name="type" required><option value="dispensed" @selected(old('type','dispensed')==='dispensed')>Dispensed to patient</option><option value="stock_out" @selected(old('type')==='stock_out')>Stock out / released</option></select></div>
    <div class="field"><label for="recipient">Recipient / patient reference</label><input class="input" id="recipient" name="recipient" value="{{ old('recipient') }}" placeholder="Use a non-sensitive reference"></div><div class="field"><label class="required" for="purpose">Purpose</label><input class="input" id="purpose" name="purpose" value="{{ old('purpose') }}" required placeholder="Patient dispensing, outreach program…"></div>
    <div class="field"><label class="required" for="transacted_at">Date and time</label><input class="input" id="transacted_at" name="transacted_at" type="datetime-local" max="{{ now()->format('Y-m-d\TH:i') }}" value="{{ old('transacted_at',now()->format('Y-m-d\TH:i')) }}" required></div><div class="field"><label for="reference_number">Reference number</label><input class="input" id="reference_number" name="reference_number" value="{{ old('reference_number') }}" placeholder="RX / release slip"></div>
    <div class="field span-2"><label for="remarks">Remarks</label><textarea class="textarea" id="remarks" name="remarks">{{ old('remarks') }}</textarea></div>
</div><div class="form-actions"><a class="btn btn-secondary" href="{{ route('dashboard') }}">Cancel</a><button class="btn btn-primary" type="submit"><x-icon name="stock-out" class="icon-sm" /> Release using FEFO</button></div></div></form>
<aside style="display:grid;gap:18px;align-content:start"><div class="card"><div class="card-header"><h2 class="card-title">FEFO protection</h2></div><div class="card-body"><div class="alert alert-success" style="box-shadow:none"><x-icon name="check" /><span><strong>Expired batches blocked</strong><br>The service only locks and consumes active, non-expired stock.</span></div><p class="card-subtitle">If the requested quantity spans multiple batches, each deduction gets its own linked transaction record.</p></div></div><div class="card"><div class="card-header"><h2 class="card-title">Privacy reminder</h2></div><div class="card-body"><p class="card-subtitle">Use a patient reference number instead of a full clinical record. This inventory system does not replace the facility’s patient record system.</p></div></div></aside>
</div>
@endsection
