@extends('layouts.app')
@section('title', 'Admin Accounts')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Admin Accounts</div><h1 class="page-title">Admin account controls</h1><p class="page-subtitle">Approve access requests and reset staff passwords securely.</p></div></div>

<section class="card"><div class="card-header"><div><h2 class="card-title">Pending access requests</h2><p class="card-subtitle">Inactive accounts cannot sign in until you approve them.</p></div><span class="badge badge-warning">{{ $pendingUsers->count() }} pending</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Staff member</th><th>Role</th><th>Requested</th><th class="text-right">Action</th></tr></thead><tbody>@forelse($pendingUsers as $pendingUser)<tr><td><strong>{{ $pendingUser->name }}</strong><span class="table-secondary">{{ $pendingUser->email }}</span></td><td><span class="badge badge-info">{{ $pendingUser->role?->name ?? 'No role' }}</span></td><td>{{ $pendingUser->created_at->format('M d, Y') }}</td><td class="text-right"><form method="POST" action="{{ route('users.approve', $pendingUser) }}" data-confirm="Approve access for {{ $pendingUser->name }}?">@csrf @method('PUT')<button class="btn btn-primary" type="submit">Approve account</button></form></td></tr>@empty<tr><td colspan="4"><div class="empty-state"><h3>No pending requests</h3><p>New staff requests will appear here after email verification.</p></div></td></tr>@endforelse</tbody></table></div></section>

<section class="card" style="margin-top:18px"><div class="card-header"><div><h2 class="card-title">Staff password resets</h2><p class="card-subtitle">Set a strong new password for a staff account. The action is recorded in the audit log.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Staff member</th><th>Role</th><th>Status</th><th>Set new password</th></tr></thead><tbody>@forelse($staffUsers as $staffUser)<tr><td><strong>{{ $staffUser->name }}</strong><span class="table-secondary">{{ $staffUser->email }}</span></td><td><span class="badge badge-info">{{ $staffUser->role?->name ?? 'No role' }}</span></td><td><x-status-badge :status="$staffUser->status" /></td><td><form method="POST" action="{{ route('admin.accounts.password.reset', $staffUser) }}" class="table-actions" data-confirm="Reset the password for {{ $staffUser->name }}?">@csrf @method('PUT')<input class="input" style="min-width:180px" name="password" type="password" autocomplete="new-password" required placeholder="New strong password"><input class="input" style="min-width:180px" name="password_confirmation" type="password" autocomplete="new-password" required placeholder="Confirm password"><button class="btn btn-secondary" type="submit">Reset password</button></form></td></tr>@empty<tr><td colspan="4"><div class="empty-state"><h3>No staff accounts found</h3></div></td></tr>@endforelse</tbody></table></div><x-pagination :paginator="$staffUsers" /></section>
@endsection
