@extends('layouts.app')
@section('title', 'Medicines')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Medicines</div><h1 class="page-title">Medicine inventory</h1><p class="page-subtitle">Search, filter, and manage the complete RHU medicine catalog and its live batch stock.</p></div><div class="page-actions">
    <a class="btn btn-secondary" href="{{ route('scanner') }}"><x-icon name="scan" class="icon-sm" /> Scan</a>
    <a class="btn btn-secondary" href="{{ route('medicines.export',request()->query()) }}"><x-icon name="download" class="icon-sm" /> Export CSV</a>
    @if(auth()->user()->hasPermission('medicines.create'))<a class="btn btn-primary" href="{{ route('medicines.create') }}"><x-icon name="plus" class="icon-sm" /> Add medicine</a>@endif
</div></div>

<form class="card filter-bar" method="GET" action="{{ route('medicines.index') }}"><div class="filters" style="grid-template-columns:2fr repeat(4,1fr) auto">
    <div class="field filter-search"><label for="search">Search inventory</label><div class="input-wrap"><x-icon name="search" class="icon-sm" /><input class="input" id="search" name="search" value="{{ request('search') }}" placeholder="Name, ID, barcode, batch, supplier…"></div></div>
    <div class="field"><label for="category">Category</label><select class="select" id="category" name="category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)request('category')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div>
    <div class="field"><label for="stock_status">Stock status</label><select class="select" id="stock_status" name="stock_status"><option value="">All statuses</option>@foreach(['normal'=>'Normal','low'=>'Low','critical'=>'Critical','out'=>'Out of stock'] as $value=>$label)<option value="{{ $value }}" @selected(request('stock_status')===$value)>{{ $label }}</option>@endforeach</select></div>
    <div class="field"><label for="expiration">Expiration</label><select class="select" id="expiration" name="expiration"><option value="">Any expiration</option><option value="expired" @selected(request('expiration')==='expired')>Expired</option>@foreach([7,30,60,90] as $days)<option value="{{ $days }}" @selected((string)request('expiration')===(string)$days)>Within {{ $days }} days</option>@endforeach</select></div>
    <div class="field"><label for="sort">Sort by</label><select class="select" id="sort" name="sort"><option value="generic_name">Generic name</option><option value="current_stock" @selected(request('sort')==='current_stock')>Current stock</option><option value="created_at" @selected(request('sort')==='created_at')>Date added</option><option value="unit_cost" @selected(request('sort')==='unit_cost')>Unit cost</option></select></div>
    <button class="btn btn-primary" type="submit"><x-icon name="adjust" class="icon-sm" /> Apply</button>
</div></form>

@if(auth()->user()->hasPermission('medicines.create'))
<details class="card" style="margin-bottom:16px"><summary style="cursor:pointer;padding:14px 18px;font-weight:650"><x-icon name="upload" class="icon-sm" style="vertical-align:middle" /> Bulk import medicines</summary><div class="card-body" style="border-top:1px solid var(--border)"><form method="POST" action="{{ route('medicines.import') }}" enctype="multipart/form-data" style="display:flex;align-items:end;gap:12px;flex-wrap:wrap">@csrf<div class="field" style="flex:1;min-width:240px"><label class="required" for="import_file">CSV file</label><input class="input" id="import_file" name="import_file" type="file" accept=".csv,text/csv" required></div><a class="btn btn-secondary" href="{{ route('medicines.template') }}"><x-icon name="download" class="icon-sm" /> Template</a><button class="btn btn-primary" type="submit"><x-icon name="upload" class="icon-sm" /> Import records</button></form></div></details>
@endif

<section class="card">
    <div class="card-header"><div><h2 class="card-title">{{ number_format($medicines->total()) }} medicine records</h2><p class="card-subtitle">Stock totals include every batch; usable stock excludes expired batches.</p></div><a class="link" href="{{ route('medicines.index') }}">Clear filters</a></div>
    <div class="table-wrap"><table class="data-table"><thead><tr><th>Medicine</th><th>Category</th><th>Form & strength</th><th>Current stock</th><th>Level</th><th>Value</th><th>Updated</th><th class="text-right">Actions</th></tr></thead><tbody>
    @forelse($medicines as $medicine)
        <tr><td><a class="table-primary" href="{{ route('medicines.show',$medicine) }}">{{ $medicine->generic_name }}</a><span class="table-secondary">{{ $medicine->brand_name ?: 'Generic' }} · <span class="mono">{{ $medicine->medicine_code }}</span></span></td><td>{{ $medicine->category->name }}</td><td>{{ $medicine->dosage_form }}<span class="table-secondary">{{ $medicine->strength ?: '—' }}</span></td><td><strong>{{ number_format($medicine->current_stock ?? 0) }}</strong> {{ $medicine->unit }}<span class="table-secondary">{{ number_format($medicine->usable_stock ?? 0) }} usable</span></td><td><x-status-badge :status="$medicine->stockStatus()" /></td><td>₱{{ number_format(($medicine->current_stock ?? 0)*(float)$medicine->unit_cost,2) }}</td><td>{{ $medicine->updated_at->format('M d, Y') }}</td><td><div class="table-actions"><a class="btn btn-secondary btn-icon" href="{{ route('medicines.show',$medicine) }}" title="View"><x-icon name="eye" class="icon-sm" /></a>@if(auth()->user()->hasPermission('medicines.edit'))<a class="btn btn-secondary btn-icon" href="{{ route('medicines.edit',$medicine) }}" title="Edit"><x-icon name="edit" class="icon-sm" /></a>@endif</div></td></tr>
    @empty<tr><td colspan="8"><div class="empty-state"><span class="empty-icon"><x-icon name="medicine" class="icon-lg" /></span><h3>No medicines found</h3><p>Try clearing the filters or add the first medicine record.</p>@if(auth()->user()->hasPermission('medicines.create'))<a class="btn btn-primary" href="{{ route('medicines.create') }}">Add medicine</a>@endif</div></td></tr>@endforelse
    </tbody></table></div><x-pagination :paginator="$medicines" />
</section>
@endsection
