@extends('layouts.app')
@section('title', 'Medicines')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Medicines</div><h1 class="page-title">{{ $showArchived ? 'Archived medicines' : 'Medicine inventory' }}</h1><p class="page-subtitle">{{ $showArchived ? 'Review medicine records retained outside the active inventory catalog.' : 'Search, filter, and manage the complete RHU medicine catalog and its live batch stock.' }}</p></div><div class="page-actions">
    @if($showArchived)<a class="btn btn-secondary" href="{{ route('medicines.index') }}"><x-icon name="chevron" class="icon-sm" /> Active medicines</a>@else
        @if(auth()->user()->hasPermission('stock.receive'))<a class="btn btn-secondary" href="{{ route('scanner') }}"><x-icon name="scan" class="icon-sm" /> Scan</a>@endif
        <a class="btn btn-secondary" href="{{ route('medicines.export', request()->query()) }}"><x-icon name="download" class="icon-sm" /> Export CSV</a>
        <a class="btn btn-secondary" href="{{ route('medicines.archived') }}"><x-icon name="audit" class="icon-sm" /> Archived medicines</a>
        @if(auth()->user()->hasPermission('medicines.create'))<a class="btn btn-primary" href="{{ route('medicines.create') }}"><x-icon name="plus" class="icon-sm" /> Add medicine</a>@endif
    @endif
</div></div>

<form class="card filter-bar" method="GET" action="{{ route($showArchived ? 'medicines.archived' : 'medicines.index') }}"><div class="filters" style="grid-template-columns:2fr repeat(4,1fr) auto">
    <div class="field filter-search"><label for="search">Search inventory</label><div class="input-wrap"><x-icon name="search" class="icon-sm" /><input class="input" id="search" name="search" value="{{ request('search') }}" placeholder="Name, ID, barcode, batch, supplier..."></div></div>
    <div class="field"><label for="category">Category</label><select class="select" id="category" name="category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) request('category') === (string) $category->id)>{{ $category->name }}</option>@endforeach</select></div>
    <div class="field"><label for="stock_status">Stock status</label><select class="select" id="stock_status" name="stock_status"><option value="">All statuses</option>@foreach(['normal' => 'Normal', 'low' => 'Low', 'critical' => 'Critical', 'out' => 'Out of stock'] as $value => $label)<option value="{{ $value }}" @selected(request('stock_status') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div class="field"><label for="expiration">Expiration</label><select class="select" id="expiration" name="expiration"><option value="">Any expiration</option><option value="expired" @selected(request('expiration') === 'expired')>Expired</option>@foreach([7, 30, 60, 90] as $days)<option value="{{ $days }}" @selected((string) request('expiration') === (string) $days)>Within {{ $days }} days</option>@endforeach</select></div>
    <div class="field"><label for="sort">Sort by</label><select class="select" id="sort" name="sort"><option value="generic_name">Generic name</option><option value="current_stock" @selected(request('sort') === 'current_stock')>Current stock</option><option value="created_at" @selected(request('sort') === 'created_at')>Date added</option><option value="unit_cost" @selected(request('sort') === 'unit_cost')>Unit cost</option></select></div>
    <button class="btn btn-primary" type="submit"><x-icon name="adjust" class="icon-sm" /> Apply</button>
</div></form>

@php($canArchiveMedicines = ! $showArchived && auth()->user()->hasPermission('medicines.edit'))
<section class="card">
    <div class="card-header"><div><h2 class="card-title">{{ number_format($medicines->total()) }} medicine records</h2><p class="card-subtitle">{{ $showArchived ? 'Archived records are read-only and excluded from active inventory.' : 'Stock totals include every batch; usable stock excludes expired batches.' }}</p></div><div class="card-header-actions">@if($canArchiveMedicines)<button class="btn btn-secondary btn-sm" type="button" data-medicine-selection-toggle="medicine-bulk-actions" aria-pressed="false">Manage medicines</button>@endif<a class="link" href="{{ route($showArchived ? 'medicines.archived' : 'medicines.index') }}">Clear filters</a></div></div>
    @if($canArchiveMedicines)
    <form id="medicine-bulk-actions" method="POST" action="{{ route('medicines.bulk-archive') }}" data-medicine-bulk-selection data-confirm="Archive the selected medicines? Their transaction history will be preserved, but they will no longer appear in active inventory.">
        @csrf @method('DELETE')
        <div class="bulk-selection-toolbar" aria-live="polite"><div class="bulk-selection-copy"><strong><span data-medicine-selection-count>0</span> selected</strong><span>Select medicine records, then archive them together.</span></div><div class="bulk-selection-actions"><button class="btn btn-secondary btn-sm" type="button" data-medicine-selection-clear disabled>Clear selection</button><button class="btn btn-danger btn-sm" type="submit" data-medicine-selection-archive disabled><x-icon name="trash" class="icon-sm" /> Archive selected</button></div></div>
    @endif
    <div class="table-wrap"><table class="data-table"><thead><tr>@if($canArchiveMedicines)<th class="medicine-selection-cell medicine-selection-column"><input class="medicine-selection-checkbox" type="checkbox" data-medicine-selection-all aria-label="Select all medicine records on this page"></th>@endif<th>Medicine</th><th>Category</th><th>Form & strength</th><th>Current stock</th><th>{{ $showArchived ? 'Archived' : 'Level' }}</th><th>Value</th><th>Updated</th><th class="text-right">Actions</th></tr></thead><tbody>
    @forelse($medicines as $medicine)
        @if($showArchived)<tr><td><span class="table-primary">{{ $medicine->generic_name }}</span><span class="table-secondary">{{ $medicine->brand_name ?: 'Generic' }} ({{ $medicine->medicine_code }})</span></td><td>{{ $medicine->category->name }}</td><td>{{ $medicine->dosage_form }}<span class="table-secondary">{{ $medicine->strength ?: 'Not specified' }}</span></td><td><strong>{{ number_format($medicine->current_stock ?? 0) }}</strong> {{ $medicine->unit }}<span class="table-secondary">{{ number_format($medicine->usable_stock ?? 0) }} usable</span></td><td><span class="badge badge-warning">{{ $medicine->deleted_at?->format('M d, Y') }}</span></td><td>&#8369;{{ number_format(($medicine->current_stock ?? 0) * (float) $medicine->unit_cost, 2) }}</td><td>{{ $medicine->updated_at->format('M d, Y') }}</td><td><div class="table-actions"><form method="POST" action="{{ route('medicines.restore', $medicine->id) }}" data-confirm="Restore {{ $medicine->generic_name }} to active inventory?">@csrf @method('PATCH')<button class="btn btn-secondary btn-sm" type="submit"><x-icon name="check" class="icon-sm" /> Restore</button></form></div></td></tr>@else
        <tr>@if($canArchiveMedicines)<td class="medicine-selection-cell medicine-selection-column"><input class="medicine-selection-checkbox" type="checkbox" name="medicine_ids[]" value="{{ $medicine->id }}" data-medicine-selection-item aria-label="Select {{ $medicine->generic_name }}"></td>@endif<td><a class="table-primary" href="{{ route('medicines.show', $medicine) }}">{{ $medicine->generic_name }}</a><span class="table-secondary">{{ $medicine->brand_name ?: 'Generic' }} &middot; <span class="mono">{{ $medicine->medicine_code }}</span></span></td><td>{{ $medicine->category->name }}</td><td>{{ $medicine->dosage_form }}<span class="table-secondary">{{ $medicine->strength ?: '—' }}</span></td><td><strong>{{ number_format($medicine->current_stock ?? 0) }}</strong> {{ $medicine->unit }}<span class="table-secondary">{{ number_format($medicine->usable_stock ?? 0) }} usable</span></td><td><x-status-badge :status="$medicine->stockStatus()" /></td><td>&#8369;{{ number_format(($medicine->current_stock ?? 0) * (float) $medicine->unit_cost, 2) }}</td><td>{{ $medicine->updated_at->format('M d, Y') }}</td><td><div class="table-actions"><a class="btn btn-secondary btn-icon" href="{{ route('medicines.show', $medicine) }}" title="View"><x-icon name="eye" class="icon-sm" /></a>@if($canArchiveMedicines)<a class="btn btn-secondary btn-icon" href="{{ route('medicines.edit', $medicine) }}" title="Edit"><x-icon name="edit" class="icon-sm" /></a>@endif</div></td></tr>
        @endif
    @empty<tr><td colspan="{{ $canArchiveMedicines ? 9 : 8 }}"><div class="empty-state"><span class="empty-icon"><x-icon name="medicine" class="icon-lg" /></span><h3>No medicines found</h3><p>Try clearing the filters or add the first medicine record.</p>@if(auth()->user()->hasPermission('medicines.create'))<a class="btn btn-primary" href="{{ route('medicines.create') }}">Add medicine</a>@endif</div></td></tr>@endforelse
    </tbody></table></div>
    @if($canArchiveMedicines)</form>@endif
    <x-pagination :paginator="$medicines" />
</section>
@endsection
