@extends('layouts.app')
@section('title','Medicine Categories')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Categories</div><h1 class="page-title">Medicine categories</h1><p class="page-subtitle">Maintain the classifications used by search, filtering, analytics, and reporting.</p></div><div class="page-actions"><a class="btn btn-primary" href="{{ route('categories.create') }}"><x-icon name="plus" class="icon-sm" /> Add category</a></div></div>
<form class="card filter-bar" method="GET"><div class="filters" style="grid-template-columns:1fr auto"><div class="field"><label for="search">Search categories</label><div class="input-wrap"><x-icon name="search" class="icon-sm" /><input class="input" id="search" name="search" value="{{ request('search') }}" placeholder="Code or category name"></div></div><button class="btn btn-primary" type="submit">Search</button></div></form>
<section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Code</th><th>Category</th><th>Description</th><th>Medicines</th><th>Status</th><th class="text-right">Actions</th></tr></thead><tbody>
@forelse($categories as $category)<tr><td class="mono">{{ $category->code }}</td><td class="table-primary">{{ $category->name }}</td><td>{{ str($category->description)->limit(70) }}</td><td><a class="link" href="{{ route('medicines.index',['category'=>$category->id]) }}">{{ $category->medicines_count }} records</a></td><td><x-status-badge :status="$category->is_active?'active':'inactive'" /></td><td><div class="table-actions"><a class="btn btn-secondary btn-icon" href="{{ route('categories.edit',$category) }}"><x-icon name="edit" class="icon-sm" /></a><form method="POST" action="{{ route('categories.destroy',$category) }}" data-confirm="Archive {{ $category->name }}? This is only allowed when it has no medicine records.">@csrf @method('DELETE')<button class="btn btn-danger btn-icon" type="submit"><x-icon name="trash" class="icon-sm" /></button></form></div></td></tr>
@empty<tr><td colspan="6"><div class="empty-state"><h3>No categories found</h3></div></td></tr>@endforelse
</tbody></table></div><x-pagination :paginator="$categories" /></section>
@endsection
