@extends('layouts.app')
@section('title','Analytics')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Analytics</div><h1 class="page-title">Inventory analytics</h1><p class="page-subtitle">Consumption patterns, demand movement, inventory value, turnover, and expiration trends from live transactions.</p></div><div class="page-actions"><a class="btn btn-secondary" href="{{ route('reports.index',['report'=>'monthly']) }}"><x-icon name="report" class="icon-sm" /> Monthly report</a></div></div>
<div class="stats-grid" style="grid-template-columns:repeat(4,minmax(0,1fr))"><div class="card stat-card"><span class="stat-icon teal"><x-icon name="money" /></span><span class="stat-copy"><span class="stat-label">Inventory value</span><span class="stat-value">₱{{ number_format($inventoryValue,2) }}</span><span class="stat-hint">Current batch cost</span></span></div><div class="card stat-card"><span class="stat-icon"><x-icon name="transaction" /></span><span class="stat-copy"><span class="stat-label">12-month volume</span><span class="stat-value">{{ number_format($totalVolume) }}</span><span class="stat-hint">Transactions</span></span></div><div class="card stat-card"><span class="stat-icon purple"><x-icon name="analytics" /></span><span class="stat-copy"><span class="stat-label">Stock turnover</span><span class="stat-value">{{ number_format($stockTurnover,2) }}×</span><span class="stat-hint">Released / current stock</span></span></div><div class="card stat-card"><span class="stat-icon amber"><x-icon name="calendar" /></span><span class="stat-copy"><span class="stat-label">Next expirations</span><span class="stat-value">{{ $expirationTrend->count() }}</span><span class="stat-hint">Batches tracked</span></span></div></div>
@php
    $monthlyChart = ['type' => 'bar', 'labels' => $monthlySeries['labels'], 'datasets' => [
        ['data' => $monthlySeries['received'], 'color' => '#0d9488'],
        ['data' => $monthlySeries['released'], 'color' => '#2885f6'],
    ]];
@endphp
<section class="card" style="margin-bottom:18px"><div class="card-header"><div><h2 class="card-title">Monthly stock movement</h2><p class="card-subtitle">Received and released quantities for the last 12 months.</p></div><div class="legend"><span class="legend-item"><i class="legend-dot" style="background:#0d9488"></i>Received</span><span class="legend-item"><i class="legend-dot" style="background:#2885f6"></i>Released</span></div></div><div class="card-body"><div class="chart-wrap"><canvas class="chart" data-chart='{{ json_encode($monthlyChart) }}'></canvas></div></div></section>
<div class="grid grid-2" style="margin-bottom:18px"><section class="card"><div class="card-header"><div><h2 class="card-title">Most frequently dispensed</h2><p class="card-subtitle">Highest released quantity over 12 months.</p></div></div><div class="card-body" style="display:grid;gap:15px">@forelse($mostDispensed as $item)<div><div style="display:flex;justify-content:space-between"><a class="table-primary" href="{{ route('medicines.show',$item['medicine']) }}">{{ $item['medicine']->generic_name }}</a><strong>{{ number_format($item['quantity']) }} {{ $item['medicine']->unit }}</strong></div><div class="progress" style="margin-top:7px"><span style="width:{{ ($item['quantity']/max(1,$mostDispensed->max('quantity')))*100 }}%"></span></div></div>@empty<p class="card-subtitle">No dispensing data yet.</p>@endforelse</div></section><section class="card"><div class="card-header"><div><h2 class="card-title">Most received medicines</h2><p class="card-subtitle">Highest receipt quantity over 12 months.</p></div></div><div class="card-body" style="display:grid;gap:15px">@forelse($mostReceived as $item)<div><div style="display:flex;justify-content:space-between"><a class="table-primary" href="{{ route('medicines.show',$item['medicine']) }}">{{ $item['medicine']->generic_name }}</a><strong>{{ number_format($item['quantity']) }} {{ $item['medicine']->unit }}</strong></div><div class="progress" style="margin-top:7px"><span style="width:{{ ($item['quantity']/max(1,$mostReceived->max('quantity')))*100 }}%"></span></div></div>@empty<p class="card-subtitle">No receipt data yet.</p>@endforelse</div></section></div>
<div class="grid grid-3"><section class="card"><div class="card-header"><h2 class="card-title">Increasing demand</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Medicine</th><th>30 days</th><th>Change</th></tr></thead><tbody>@forelse($increasingDemand as $item)<tr><td>{{ $item['medicine']->generic_name }}</td><td>{{ $item['current'] }}</td><td><span class="badge badge-success">+{{ $item['change'] }}%</span></td></tr>@empty<tr><td colspan="3">No increasing trend.</td></tr>@endforelse</tbody></table></div></section><section class="card"><div class="card-header"><h2 class="card-title">Decreasing demand</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Medicine</th><th>30 days</th><th>Change</th></tr></thead><tbody>@forelse($decreasingDemand as $item)<tr><td>{{ $item['medicine']->generic_name }}</td><td>{{ $item['current'] }}</td><td><span class="badge badge-warning">{{ $item['change'] }}%</span></td></tr>@empty<tr><td colspan="3">No decreasing trend.</td></tr>@endforelse</tbody></table></div></section><section class="card"><div class="card-header"><h2 class="card-title">Expiration trend</h2></div><div class="card-body" style="display:grid;gap:11px">@foreach($expirationTrend as $batch)<a class="notification-item" href="{{ route('medicines.show',$batch->medicine) }}" style="padding:5px"><span class="notification-icon {{ in_array($batch->expirationStatus(),['expired','7_days'])?'danger':'warning' }}"><x-icon name="calendar" class="icon-sm" /></span><span class="notification-copy"><strong>{{ $batch->medicine->generic_name }}</strong><p>{{ $batch->batch_number }} · {{ $batch->expiration_date->format('M d, Y') }}</p></span></a>@endforeach</div></section></div>
@endsection
