@extends('layouts.app')
@section('title',$supplier->exists?'Edit Supplier':'Add Supplier')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('suppliers.index') }}">Suppliers</a><x-icon name="chevron" class="icon-sm" /> {{ $supplier->exists?'Edit':'Add' }}</div><h1 class="page-title">{{ $supplier->exists?'Edit supplier':'Add supplier' }}</h1><p class="page-subtitle">Record procurement contact and registration details.</p></div></div>
<form class="card" method="POST" action="{{ $supplier->exists?route('suppliers.update',$supplier):route('suppliers.store') }}">@csrf @if($supplier->exists)@method('PUT')@endif<div class="card-header"><h2 class="card-title">Supplier details</h2></div><div class="card-body"><div class="form-grid">
<div class="field"><label class="required" for="code">Supplier ID</label><input class="input mono" id="code" name="code" value="{{ old('code',$supplier->code) }}" required></div><div class="field"><label class="required" for="name">Supplier name</label><input class="input" id="name" name="name" value="{{ old('name',$supplier->name) }}" required></div>
<div class="field"><label for="contact_person">Contact person</label><input class="input" id="contact_person" name="contact_person" value="{{ old('contact_person',$supplier->contact_person) }}"></div><div class="field"><label for="license_number">License / registration</label><input class="input" id="license_number" name="license_number" value="{{ old('license_number',$supplier->license_number) }}"></div>
<div class="field"><label for="phone">Phone</label><input class="input" id="phone" name="phone" value="{{ old('phone',$supplier->phone) }}"></div><div class="field"><label for="email">Email</label><input class="input" id="email" name="email" type="email" value="{{ old('email',$supplier->email) }}"></div>
<div class="field span-2"><label for="address">Address</label><textarea class="textarea" id="address" name="address">{{ old('address',$supplier->address) }}</textarea></div><div class="field span-2"><label for="notes">Notes</label><textarea class="textarea" id="notes" name="notes">{{ old('notes',$supplier->notes) }}</textarea></div>
<div class="field"><label class="required" for="is_active">Status</label><select class="select" id="is_active" name="is_active"><option value="1" @selected(old('is_active',$supplier->is_active)!==false)>Active</option><option value="0" @selected((string)old('is_active',$supplier->is_active)==='0')>Inactive</option></select></div>
</div><div class="form-actions"><a class="btn btn-secondary" href="{{ $supplier->exists?route('suppliers.show',$supplier):route('suppliers.index') }}">Cancel</a><button class="btn btn-primary" type="submit">{{ $supplier->exists?'Save changes':'Create supplier' }}</button></div></div></form>
@endsection
