@extends('layouts.app')
@section('title','Suppliers')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Suppliers</div><h1 class="page-title">Supplier management</h1><p class="page-subtitle">Manage approved suppliers and trace received batches back to their source.</p></div><div class="page-actions"><a class="btn btn-primary" href="{{ route('suppliers.create') }}"><x-icon name="plus" class="icon-sm" /> Add supplier</a></div></div>
<form class="card filter-bar" method="GET"><div class="filters" style="grid-template-columns:1fr auto"><div class="field"><label for="search">Search suppliers</label><div class="input-wrap"><x-icon name="search" class="icon-sm" /><input class="input" id="search" name="search" value="{{ request('search') }}" placeholder="Name, code, or contact person"></div></div><button class="btn btn-primary" type="submit">Search</button></div></form>
<section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Supplier</th><th>Contact</th><th>Phone / email</th><th>License</th><th>Batches</th><th>Status</th><th class="text-right">Actions</th></tr></thead><tbody>
@forelse($suppliers as $supplier)<tr><td><a class="table-primary" href="{{ route('suppliers.show',$supplier) }}">{{ $supplier->name }}</a><span class="table-secondary mono">{{ $supplier->code }}</span></td><td>{{ $supplier->contact_person ?: '—' }}</td><td>{{ $supplier->phone ?: '—' }}<span class="table-secondary">{{ $supplier->email ?: 'No email' }}</span></td><td class="mono">{{ $supplier->license_number ?: '—' }}</td><td>{{ $supplier->batches_count }}</td><td><x-status-badge :status="$supplier->is_active?'active':'inactive'" /></td><td><div class="table-actions"><a class="btn btn-secondary btn-icon" href="{{ route('suppliers.show',$supplier) }}"><x-icon name="eye" class="icon-sm" /></a><a class="btn btn-secondary btn-icon" href="{{ route('suppliers.edit',$supplier) }}"><x-icon name="edit" class="icon-sm" /></a></div></td></tr>
@empty<tr><td colspan="7"><div class="empty-state"><h3>No suppliers found</h3></div></td></tr>@endforelse
</tbody></table></div><x-pagination :paginator="$suppliers" /></section>
@endsection
