@extends('layouts.app')
@section('title','Settings')
@section('content')
<div class="page-header"><div><div class="breadcrumb"><a href="{{ route('dashboard') }}">Dashboard</a><x-icon name="chevron" class="icon-sm" /> Settings</div><h1 class="page-title">System settings</h1><p class="page-subtitle">Configure facility identity, inventory defaults, notifications, timezone, and appearance.</p></div></div>
<form method="POST" action="{{ route('settings.update') }}">@csrf @method('PUT')<div class="grid grid-2">
<section class="card"><div class="card-header"><div><h2 class="card-title">Facility identity</h2><p class="card-subtitle">Displayed across navigation and printed reports.</p></div><span class="stat-icon teal"><x-icon name="medicine" /></span></div><div class="card-body"><div class="form-grid"><div class="field"><label class="required" for="system_name">System name</label><input class="input" id="system_name" name="system_name" value="{{ old('system_name',$settings['system_name']??'MediStock RHU') }}" required></div><div class="field"><label class="required" for="facility_name">RHU / clinic name</label><input class="input" id="facility_name" name="facility_name" value="{{ old('facility_name',$settings['facility_name']??'') }}" required></div><div class="field"><label for="contact_phone">Phone</label><input class="input" id="contact_phone" name="contact_phone" value="{{ old('contact_phone',$settings['contact_phone']??'') }}"></div><div class="field"><label for="contact_email">Email</label><input class="input" id="contact_email" name="contact_email" type="email" value="{{ old('contact_email',$settings['contact_email']??'') }}"></div><div class="field span-2"><label for="address">Address</label><textarea class="textarea" id="address" name="address">{{ old('address',$settings['address']??'') }}</textarea></div></div></div></section>
<section class="card"><div class="card-header"><div><h2 class="card-title">Inventory alerts</h2><p class="card-subtitle">Default thresholds and alert delivery.</p></div><span class="stat-icon amber"><x-icon name="alert" /></span></div><div class="card-body"><div class="form-grid"><div class="field"><label class="required" for="low_stock_threshold">Default low-stock threshold</label><input class="input" id="low_stock_threshold" name="low_stock_threshold" type="number" min="0" value="{{ old('low_stock_threshold',$settings['low_stock_threshold']??10) }}" required></div><div class="field"><label class="required" for="expiration_warning_days">Expiration warning days</label><input class="input" id="expiration_warning_days" name="expiration_warning_days" type="number" min="1" max="365" value="{{ old('expiration_warning_days',$settings['expiration_warning_days']??90) }}" required></div><div class="field span-2"><input type="hidden" name="notification_low_stock" value="0"><label class="checkbox-row"><input name="notification_low_stock" type="checkbox" value="1" @checked(old('notification_low_stock',$settings['notification_low_stock']??'1'))><span><strong>Low-stock notifications</strong><small class="table-secondary">Notify when a medicine reaches low, critical, or zero stock.</small></span></label></div><div class="field span-2"><input type="hidden" name="notification_expiration" value="0"><label class="checkbox-row"><input name="notification_expiration" type="checkbox" value="1" @checked(old('notification_expiration',$settings['notification_expiration']??'1'))><span><strong>Expiration notifications</strong><small class="table-secondary">Notify when active batches enter the warning window.</small></span></label></div></div></div></section>
<section class="card"><div class="card-header"><div><h2 class="card-title">Regional preferences</h2><p class="card-subtitle">Formatting and local time behavior.</p></div></div><div class="card-body"><div class="form-grid"><div class="field"><label class="required" for="date_format">Date format</label><select class="select" id="date_format" name="date_format">@foreach(['M d, Y'=>'Aug 24, 2026','d/m/Y'=>'24/08/2026','m/d/Y'=>'08/24/2026','Y-m-d'=>'2026-08-24'] as $value=>$label)<option value="{{ $value }}" @selected(old('date_format',$settings['date_format']??'M d, Y')===$value)>{{ $label }}</option>@endforeach</select></div><div class="field"><label class="required" for="timezone">Timezone</label><select class="select" id="timezone" name="timezone"><option value="Asia/Manila" @selected(old('timezone',$settings['timezone']??'Asia/Manila')==='Asia/Manila')>Asia/Manila (PHT)</option><option value="UTC" @selected(old('timezone',$settings['timezone']??'')==='UTC')>UTC</option><option value="Asia/Singapore" @selected(old('timezone',$settings['timezone']??'')==='Asia/Singapore')>Asia/Singapore</option></select></div></div></div></section>
<section class="card"><div class="card-header"><div><h2 class="card-title">Appearance</h2><p class="card-subtitle">Default theme for new sessions.</p></div></div><div class="card-body"><div class="field"><label class="required" for="default_theme">Default theme</label><select class="select" id="default_theme" name="default_theme"><option value="system" @selected(old('default_theme',$settings['default_theme']??'system')==='system')>Follow device</option><option value="light" @selected(old('default_theme',$settings['default_theme']??'')==='light')>Light</option><option value="dark" @selected(old('default_theme',$settings['default_theme']??'')==='dark')>Dark</option></select></div><div class="alert alert-success" style="margin-top:18px;box-shadow:none"><x-icon name="info" /><span>Each user can override the default theme in their profile or from the top navigation.</span></div></div></section>
</div><div class="form-actions"><a class="btn btn-secondary" href="{{ route('dashboard') }}">Cancel</a><button class="btn btn-primary" type="submit"><x-icon name="check" class="icon-sm" /> Save settings</button></div></form>
@endsection
